# Harvester Cluster
endpoint: 'https://10.10.0.100'
username: 'admin'
password: 'admin'
# Be used to access Harvester node, fill in one of following is enough.
host-password: 'p@ssword'
host-private-key: ''

# VLAN ID, will invoke the tests depended on external networking if not set to -1.
vlan-id: 1
# Physical NIC for VLAN. Default is "harvester-mgmt"
vlan-nic: 'harvester-mgmt'
ip-pool-subnet: '192.168.0.0/24'

# Wait time for polling operations
wait-timeout: 600
# Sleep time for polling operations
sleep-timeout: 3

# script location to manipulate node power cycle
node-scripts-location: 'scripts/vagrant'

opensuse-image-url: http://172.19.96.23/iso/openSUSE/openSUSE-Leap-15.5.x86_64-NoCloud.qcow2
ubuntu-image-url: http://172.19.96.23/iso/ubuntu/jammy-server-cloudimg-amd64-current.img
# URL to download all images
image-cache-url: ''

# script location for terraform related test cases
terraform-scripts-location: 'terraform_test_artifacts'
terraform-provider-rancher: '3.1.1'

# Backup Target S3
s3-endpoint: 'http://172.19.104.200:9000'
region: 'pcloud'
accessKeyId: 'minioadmin'
secretAccessKey: 'minioadmin'
bucketName: 'test'

# Backup Targer NFS
nfs-endpoint: ''
nfs-mount-dir: 'nfsshare'

# Rancher Cluster
rancher-endpoint: 'https://127.0.0.1'
rancher-admin-password: 'rancher_password'
# Prefix of K8s version for to create downstream cluster
k8s-version: 'v1.27'
# Wait time for polling Rancher cluster status.
rancher-cluster-wait-timeout: 7200

# Upgrade parameters
upgrade-prepare-dependence: False
upgrade-sc-replicas: 3
# If the value is empty, then skip the os version validation.
upgrade-target-version: ""
upgrade-iso-url: ""
upgrade-iso-checksum: ""
# Based on the number of nodes, i.e., upgrade-wait-timeout * 3 nodes
upgrade-wait-timeout: 7200
