FROM python:3.8.13-buster
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential findutils wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV DAPPER_SOURCE /app
ENV DAPPER_RUN_ARGS --network host

ENV HOME ${DAPPER_SOURCE}
ENV DAPPER_OUTPUT ./results
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./dapper-scripts/entry"]
CMD ["default"]

